# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - app-memoryland

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Create appsettings.json
        run: |
          cat <<EOL > memoryland-backend/WebApi/appsettings.json
          {
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*",
            "UseLocalDb": false,
            "ConnectionStrings": {
              "BlobStorageDefault": "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}",
              "Default": "${{ secrets.POSTGRES_CONNECTION_STRING }}"
            },
            "AzureAdB2C": {
              "Instance": "${{ secrets.AD_B2C_INSTANCE }}",
              "ClientId": "${{ secrets.AD_B2C_CLIENT_ID }}",
              "Domain": "${{ secrets.AD_B2C_DOMAIN }}",
              "SignedOutCallbackPath": "${{ secrets.AD_B2C_SIGNED_OUT_CALLBACK_PATH }}",
              "SignUpSignInPolicyId": "${{ secrets.AD_B2C_SIGN_UP_SIGN_IN_POLICY_ID }}",
            }
          }
          EOL
        shell: bash

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build memoryland-backend/WebApi/WebApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish memoryland-backend/WebApi/WebApi.csproj -c Release -o "${{github.workspace}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
      actions: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DDCBF407193A4A5DB844098BB16ACB44 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96D2D4FE0950499D9A2EE4CE9632CE91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45C62F7BB6FA4690B4765D2630FEB0F9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-memoryland'
          slot-name: 'Production'
          package: .

      - name: Delete artifact after deployment
        if: always()
        uses: geekyeggo/delete-artifact@v4
        with:
          name: .net-app
